DROP TABLE IF EXISTS Stats;

CREATE TABLE IF NOT EXISTS Stats
(
    id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    app       VARCHAR(255)                NOT NULL,
    uri       VARCHAR(255)                NOT NULL,
    ip        varchar(64)                 NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);